spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testjwt?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true
    username: admin
    password: 123456
mybatis:
  config-location: classpath:mybatis.xml
server:
  port: 8889


logging:
  level:
    com.pjb.springbootjjwt: DEBUG